# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('design_image', models.ImageField(blank=True, null=True, upload_to='embroidery_designs/')),
                ('fabric_type', models.CharField(blank=True, max_length=50, null=True)),
                ('thread_type', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('complexity_level', models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], default='simple', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embroideries', to='tailor.tailor')),
            ],
        ),
    ]
