# Generated by Django 5.2.5 on 2025-08-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.CharField(blank=True, max_length=10, null=True)),
                ('waist', models.CharField(blank=True, max_length=10, null=True)),
                ('hip', models.CharField(blank=True, max_length=10, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=10, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=10, null=True)),
                ('neck', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.CharField(blank=True, max_length=10, null=True)),
                ('inseam', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customer_profiles/')),
            ],
        ),
    ]
