# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('pre_designed', '0001_initial'),
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customer.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dress_reviews', to='pre_designed.predesigned')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailor_reviews', to='tailor.tailor')),
            ],
            options={
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
