# Generated by Django 5.2.5 on 2025-10-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('tailor', '0008_tailor_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tailor_reviews', to='tailor.tailor'),
        ),
    ]
