# Generated by Django 5.2.5 on 2025-10-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('reviews', '0002_alter_reviews_tailor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='customer.customer'),
        ),
    ]
