# Generated by Django 5.2.5 on 2025-08-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tailor.tailor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tailors', to='customer.customer')),
            ],
        ),
    ]
