# Generated by Django 5.2.5 on 2025-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('short_punjabi', 'Short Punjabi'), ('long_punjabi', 'Long Punjabi'), ('designer_punjabi', 'Designer Punjabi'), ('embroidered_punjabi', 'Embroidered Punjabi'), ('kurta_punjabi', 'Kurta Punjabi'), ('traditional_punjabi', 'Traditional Punjabi'), ('formal_shirt', 'Formal Shirt'), ('casual_shirt', 'Casual Shirt'), ('half_sleeve_shirt', 'Half Sleeve Shirt'), ('denim_shirt', 'Denim Shirt'), ('tshirt', 'T-Shirt'), ('sleeveless_shirt', 'Sleeveless Shirt'), ('printed_shirt', 'Printed Shirt'), ('kurta', 'Kurta'), ('formal_pant', 'Formal Pant'), ('jeans', 'Jeans'), ('cargo_pant', 'Cargo Pant'), ('chinos', 'Chinos'), ('trouser', 'Trouser'), ('shorts', 'Shorts'), ('leggings', 'Leggings'), ('salwar_kameez', 'Salwar Kameez'), ('lehenga', 'Lehenga'), ('blouse', 'Blouse'), ('saree_fall_pleat', 'Saree Fall & Pleat'), ('gown', 'Gown'), ('maxi_dress', 'Maxi Dress'), ('anarkali', 'Anarkali'), ('skirt', 'Skirt'), ('palazzo', 'Palazzo'), ('tops', 'Tops'), ('kameez', 'Kameez'), ('saree_blouse', 'Saree Blouse'), ('waistcoat', 'Waistcoat'), ('jacket', 'Jacket'), ('coat', 'Coat'), ('sherwani', 'Sherwani'), ('kids_dress', 'Kids Dress')], default='None', max_length=50, null=True),
        ),
    ]
