# Generated by Django 5.2.5 on 2025-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_order', '0002_order_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Salwar Kameez', 'Salwar Kameez'), ('Punjabi', 'Punjabi'), ('Formal ', 'Formal '), ('Casual Wear', 'Casual Wear'), ('Western Wear', 'Western Wear')], default='None', max_length=50, null=True),
        ),
    ]
