# Generated by Django 5.2.5 on 2025-10-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dress_order', '0004_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
