# Generated by Django 5.2.5 on 2025-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_order', '0005_remove_order_created_at_remove_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='production',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
