# Generated by Django 5.2.5 on 2025-10-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dress_order', '0006_order_deliver_order_order_confirmed_order_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_confirmed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='production',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quality_check',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
