# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order', models.CharField(choices=[('order_placed', 'Order Placed'), ('measurement_confirmed', 'Measurement Confirmed'), ('fabric_selected', 'Fabric Selected'), ('design_approved', 'Design Approved'), ('cutting_started', 'Cutting Started'), ('stitching_started', 'Stitching Started'), ('order_completed', 'Order Completed'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled')], default='order_placed', max_length=50)),
                ('garment_size', models.CharField(max_length=20)),
                ('fabrics', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chest', models.CharField(blank=True, max_length=10, null=True)),
                ('waist', models.CharField(blank=True, max_length=10, null=True)),
                ('hip', models.CharField(blank=True, max_length=10, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=10, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=10, null=True)),
                ('neck', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.CharField(blank=True, max_length=10, null=True)),
                ('inseam', models.CharField(blank=True, max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torders', to='customer.customer')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torders', to='tailor.tailor')),
            ],
        ),
    ]
