# Generated by Django 5.2.5 on 2025-08-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='date',
        ),
    ]
