# Generated by Django 5.2.5 on 2025-10-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0003_torders_category'),
        ('embroidery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='description',
        ),
        migrations.AddField(
            model_name='torders',
            name='embroidery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torders', to='embroidery.embroidery'),
        ),
        migrations.AddField(
            model_name='torders',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
