# Generated by Django 5.2.5 on 2025-10-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0004_remove_torders_description_torders_embroidery_and_more'),
        ('embroidery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='embroidery',
        ),
        migrations.AddField(
            model_name='torders',
            name='embroider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torders', to='embroidery.embroidery'),
        ),
    ]
