# Generated by Django 5.2.5 on 2025-10-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0005_remove_torders_embroidery_torders_embroider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torders',
            old_name='embroider',
            new_name='embroidery',
        ),
    ]
