# Generated by Django 5.2.5 on 2025-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0006_rename_embroider_torders_embroidery'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='cutting_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='deliver',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='fabric_selected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='measurements_confirmed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='stitching_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
