# Generated by Django 5.2.5 on 2025-10-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0007_torders_cutting_started_torders_deliver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torders',
            name='cutting_started',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torders',
            name='deliver',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torders',
            name='fabric_selected',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torders',
            name='measurements_confirmed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torders',
            name='stitching_started',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
