# Generated by Django 5.2.5 on 2025-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0008_alter_torders_cutting_started_alter_torders_deliver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='garment_size',
        ),
        migrations.RemoveField(
            model_name='torders',
            name='order',
        ),
        migrations.RemoveField(
            model_name='torders',
            name='status',
        ),
        migrations.AddField(
            model_name='torders',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='garment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='inspiration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='occasion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='torders',
            name='fabrics',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
