# Generated by Django 5.2.5 on 2025-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0009_remove_torders_garment_size_remove_torders_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
