# Generated by Django 5.2.5 on 2025-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0010_torders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
