# Generated by Django 5.2.5 on 2025-10-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0011_torders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='fabric_length_needed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='torders',
            name='fabric_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
