# Generated by Django 5.2.5 on 2025-10-17 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0012_torders_fabric_length_needed_torders_fabric_price'),
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='fabric_length_needed',
        ),
        migrations.RemoveField(
            model_name='torders',
            name='fabric_price',
        ),
        migrations.AlterField(
            model_name='torders',
            name='fabrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torders', to='fabrics.fabric'),
        ),
    ]
