# Generated by Django 5.2.5 on 2025-10-17 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0015_alter_torders_fabrics'),
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torders',
            name='fabrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torders', to='fabrics.fabric'),
        ),
    ]
