# Generated by Django 5.2.5 on 2025-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0016_alter_torders_fabrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='fabric_length_needed',
        ),
        migrations.RemoveField(
            model_name='torders',
            name='fabric_price',
        ),
    ]
