# Generated by Django 5.2.5 on 2025-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0017_remove_torders_fabric_length_needed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torders',
            name='fabrics',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
