# Generated by Django 5.2.5 on 2025-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0020_remove_torders_fabric_length_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='meter',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in meters', max_digits=10),
        ),
    ]
