# Generated by Django 5.2.5 on 2025-10-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0021_torders_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torders',
            name='color',
        ),
    ]
