# Generated by Django 5.2.5 on 2025-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_order', '0022_remove_torders_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='torders',
            name='embroidery_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='torders',
            name='fabric_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='torders',
            name='selected_embroidery_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
