# Generated by Django 5.2.5 on 2025-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_designed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predesigned',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='predesigned',
            name='category',
            field=models.CharField(blank=True, choices=[('saree', 'Saree'), ('salwar_kameez', 'Salwar Kameez'), ('punjabi', 'Punjabi'), ('formal shirt', 'Formal Shirt'), ('casual wear', 'Casual Wear'), ('western wear', 'Western Wear')], max_length=100, null=True),
        ),
    ]
