# Generated by Django 5.2.5 on 2025-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_designed', '0002_predesigned_gender_alter_predesigned_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predesigned',
            name='category',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Salwar Kameez', 'Salwar Kameez'), ('Punjabi', 'Punjabi'), ('Formal Shirt', 'Formal Shirt'), ('Casual Wear', 'Casual Wear'), ('Western Wear', 'Western Wear')], max_length=100, null=True),
        ),
    ]
