# Generated by Django 5.2.5 on 2025-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_designed', '0004_alter_predesigned_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predesigned',
            name='category',
            field=models.CharField(blank=True, choices=[('Saree', 'Saree'), ('Salwar Kameez', 'Salwar Kameez'), ('Punjabi', 'Punjabi'), ('Formal Wear', 'Formal Wear'), ('Casual Wear', 'Casual Wear'), ('Western Wear', 'Western Wear'), ('Suits & Blazers', 'Suits & Blazers')], max_length=100, null=True),
        ),
    ]
