# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('fabric_type', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('linen', 'Linen'), ('wool', 'Wool'), ('polyester', 'Polyester'), ('blend', 'Blend'), ('other', 'Other')], default='cotton', max_length=50)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('pattern', models.CharField(choices=[('plain', 'Plain'), ('striped', 'Striped'), ('checked', 'Checked'), ('printed', 'Printed'), ('embroidered', 'Embroidered')], default='plain', max_length=50)),
                ('texture', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, help_text='Fabric width in inches/cm', max_digits=6)),
                ('length_available', models.DecimalField(decimal_places=2, default=0.0, help_text='Available fabric in meters', max_digits=10)),
                ('price_per_meter', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabric_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='tailor.tailor')),
            ],
        ),
    ]
