# Generated by Django 5.2.5 on 2025-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='meter',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length in meters', max_digits=10),
        ),
    ]
