# Generated by Django 5.2.5 on 2025-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_fabric_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='meter',
        ),
        migrations.AddField(
            model_name='fabric',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
