# Generated by Django 5.2.5 on 2025-10-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_remove_fabric_meter_fabric_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric',
            name='total_price',
        ),
    ]
