# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_location', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('expertise', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('short_punjabi', 'Short Punjabi'), ('long_punjabi', 'Long Punjabi'), ('designer_punjabi', 'Designer Punjabi'), ('embroidered_punjabi', 'Embroidered Punjabi'), ('kurta_punjabi', 'Kurta Punjabi'), ('traditional_punjabi', 'Traditional Punjabi'), ('formal_shirt', 'Formal Shirt'), ('casual_shirt', 'Casual Shirt'), ('half_sleeve_shirt', 'Half Sleeve Shirt'), ('denim_shirt', 'Denim Shirt'), ('tshirt', 'T-Shirt'), ('sleeveless_shirt', 'Sleeveless Shirt'), ('printed_shirt', 'Printed Shirt'), ('kurta', 'Kurta'), ('formal_pant', 'Formal Pant'), ('jeans', 'Jeans'), ('cargo_pant', 'Cargo Pant'), ('chinos', 'Chinos'), ('trouser', 'Trouser'), ('shorts', 'Shorts'), ('leggings', 'Leggings'), ('salwar_kameez', 'Salwar Kameez'), ('lehenga', 'Lehenga'), ('blouse', 'Blouse'), ('saree_fall_pleat', 'Saree Fall & Pleat'), ('gown', 'Gown'), ('maxi_dress', 'Maxi Dress'), ('anarkali', 'Anarkali'), ('skirt', 'Skirt'), ('palazzo', 'Palazzo'), ('tops', 'Tops'), ('kameez', 'Kameez'), ('saree_blouse', 'Saree Blouse'), ('waistcoat', 'Waistcoat'), ('jacket', 'Jacket'), ('coat', 'Coat'), ('sherwani', 'Sherwani'), ('kids_dress', 'Kids Dress')], default='None', max_length=50, null=True)),
                ('services_offered', models.TextField(blank=True, default='None', null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('NID', models.CharField(max_length=20, unique=True)),
                ('purchased_products', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tailor_profiles/')),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('Chest', models.CharField(blank=True, max_length=10, null=True)),
                ('waist', models.CharField(blank=True, max_length=10, null=True)),
                ('hip', models.CharField(blank=True, max_length=10, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=10, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=10, null=True)),
                ('neck', models.CharField(blank=True, max_length=10, null=True)),
                ('length', models.CharField(blank=True, max_length=10, null=True)),
                ('inseam', models.CharField(blank=True, max_length=10, null=True)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
