# Generated by Django 5.2.5 on 2025-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='tailor_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
