# Generated by Django 5.2.5 on 2025-09-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
        ('tailor', '0002_tailor_business_description_tailor_tailor_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='Chest',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='hip',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='inseam',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='length',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='shoulder',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='sleeve',
        ),
        migrations.RemoveField(
            model_name='tailor',
            name='waist',
        ),
        migrations.AlterField(
            model_name='tailor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailor', to='customer.customer'),
        ),
    ]
