# Generated by Django 5.2.5 on 2025-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0005_alter_tailor_category_alter_tailor_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
