# Generated by Django 5.2.5 on 2025-10-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0006_tailor_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='address',
        ),
    ]
