# Generated by Django 5.2.5 on 2025-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0007_remove_tailor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='district',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('sylhet', 'Sylhet'), ('barisal', 'Barisal'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh'), ('comilla', 'Comilla'), ('gazipur', 'Gazipur')], max_length=100, null=True),
        ),
    ]
