# Generated by Django 5.2.5 on 2025-10-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0008_tailor_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='category',
            field=models.CharField(blank=True, choices=[('Short_Punjabi', 'Short Punjabi'), ('Long_Punjabi', 'Long Punjabi'), ('Designer_Punjabi', 'Designer Punjabi'), ('Embroidered_Punjabi', 'Embroidered Punjabi'), ('Kurta_Punjabi', 'Kurta Punjabi'), ('Traditional_Punjabi', 'Traditional Punjabi'), ('Formal_Shirt', 'Formal Shirt'), ('Casual_Shirt', 'Casual Shirt'), ('Half_Sleeve_Shirt', 'Half Sleeve Shirt'), ('Denim_Shirt', 'Denim Shirt'), ('T_Shirt', 'T-Shirt'), ('Sleeveless_Shirt', 'Sleeveless Shirt'), ('Printed_Shirt', 'Printed Shirt'), ('Kurta', 'Kurta'), ('Formal_Pant', 'Formal Pant'), ('Jeans', 'Jeans'), ('Cargo_Pant', 'Cargo Pant'), ('Chinos', 'Chinos'), ('Trouser', 'Trouser'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('Salwar_Kameez', 'Salwar Kameez'), ('Lehenga', 'Lehenga'), ('Blouse', 'Blouse'), ('Saree_Fall_Pleat', 'Saree Fall & Pleat'), ('Gown', 'Gown'), ('Maxi_Dress', 'Maxi Dress'), ('Anarkali', 'Anarkali'), ('Skirt', 'Skirt'), ('Palazzo', 'Palazzo'), ('Tops', 'Tops'), ('Kameez', 'Kameez'), ('Saree_Blouse', 'Saree Blouse'), ('Waistcoat', 'Waistcoat'), ('Jacket', 'Jacket'), ('Coat', 'Coat'), ('Sherwani', 'Sherwani'), ('Kids_Dress', 'Kids Dress')], default='Formal_Shirt', max_length=50, null=True),
        ),
    ]
